name: Build and Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-and-scan:
    name: Unit Tests + SonarQube + Docker Build
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Install dependencies and run tests with coverage
      - name: Install dependencies and Run Unit Tests with Coverage
        run: |
          pip install flask pytest pytest-cov
          python -m pytest src/test_app.py --cov=src --cov-report=xml:coverage.xml -v

      # SonarQube Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          extra-properties: |
            sonar.projectKey=JOSHUACRAZES_SSDLS
            sonar.organization=joshuacrazes
            sonar.sources=src
            sonar.python.coverage.reportPaths=coverage.xml
            sonar.coverage.exclusions=**/*test*.py
            sonar.cpd.exclusions=**/*test*.py
            sonar.verbose=true

      # Build Docker Image only (no push)
      - name: Build Docker Image
        run: |
          docker build -t cavinjoshua/myapp:latest .
