name: Build, Test, SonarQube & ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:

  build_test_sonar:
    name: Build, Test & SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests with Coverage
        run: |
          pip install pytest pytest-cov
          pytest --cov=. --cov-report=xml

      

  zap_scan:
    name: OWASP ZAP Full Security Scan
    needs: build_test_sonar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Build Docker image for Python App
      - name: Build Docker Image
        run: docker build -t myapp .

      # Run the container
      - name: Run Docker Container
        run: |
          docker run -d --name myapp -p 8000:8000 myapp
          sleep 20

      # Run ZAP Full Scan
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.13.0
        with:
          target: "http://localhost:8000"
          token: ${{ secrets.GITHUB_TOKEN }}
          cmd_options: "-a"        # Active scan enabled

      - name: Stop Docker
        run: docker stop myapp
